### ISSUE TITLE
Register in the general registry?

### ISSUE THREAD

**Issue by thchr** [JuhaHeiskala/DirectQhull.jl#6]
Hi @JuhaHeiskala, I'm wondering if you could be convinced to register this package general registry?

For a long time, I have wanted to ditch a PyCall.jl dependency (for SciPy access to qhull) in a package of mine (see https://github.com/thchr/Brillouin.jl/issues/22) - but there wasn't any sufficiently feature-complete or platform-independent Julia-version of qhull until now. If I could depend on DirectQhull.jl, it would be a breeze to dump the PyCall.jl dependency.

In principle, it would probably be better to merge somehow with the existing Qhull.jl and MiniQhull.jl packages - but I imagine that's also much more work. From my perspective, I'd just be happy to have a working solution (thanks a ton for creating this, incidentally!).

**Comment by JuhaHeiskala** [comment]
You mean the current version?
Yes, I was looking into how to update to version to the Registry.

**Comment by JuhaHeiskala** [comment]
under construction
https://github.com/JuliaRegistries/General/pull/73272

**Comment by JuhaHeiskala** [comment]
Updated in registry.
